spring:
    profile: 
        active:
            - dev
---
server:
    port: 8021

spring:
    profiles: dev
    application:
        name: springclouddemo-springcould-client-3355
        
eureka:
    client:
        server-url:
            defaultZone: http://eureka-dev.com:7001/eureka/

---

server:
    port: 8022
spring:
    profiles: test
    application:
        name: springclouddemo-springcould-client-3355
        
eureka:
    client:
        server-url:
            defaultZone: http://eureka-test.com:7001/eureka/
